openapi: 3.0.3
info:
  title: Billing API
  description: API for billing management with CQRS pattern
  version: 1.0.0
servers:
  - url: http://localhost:8080/billing
tags:
  - name: Billing Query
    description: Read operations (CQRS Query side)
  - name: Billing Command
    description: Write operations (CQRS Command side)
paths:
  /:
    get:
      tags:
        - Billing Query
      summary: Get service info
      description: Returns basic service information
      operationId: getServiceInfo
      responses:
        '200':
          description: Service information
          content:
            text/plain:
              schema:
                type: string
  /health:
    get:
      tags:
        - Billing Query
      summary: Health check
      description: Returns service health status
      operationId: getHealth
      responses:
        '200':
          description: Health status
          content:
            text/plain:
              schema:
                type: string
  /invoices:
    get:
      tags:
        - Billing Query
      summary: Get all invoices
      description: Returns list of all invoices
      operationId: getAllInvoices
      responses:
        '200':
          description: List of invoices
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Invoice'
    post:
      tags:
        - Billing Command
      summary: Create invoice
      description: Creates a new invoice
      operationId: createInvoice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Invoice'
      responses:
        '201':
          description: Invoice created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invoice'
components:
  schemas:
    Invoice:
      type: object
      required:
        - customerId
        - amount
        - status
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        customerId:
          type: integer
          format: int64
          minimum: 1
        amount:
          type: number
          format: double
          minimum: 0.01
          exclusiveMinimum: false
        status:
          type: string
          enum: [PENDING, PAID, CANCELLED]
